{"name": "test_login2", "status": "failed", "statusDetails": {"message": "AssertionError: assert '验证码不正确' == '验证码不正确，请重新输入'\n  - 验证码不正确，请重新输入\n  + 验证码不正确", "trace": "self = <scripts.test01_login.TestLogin testMethod=test_login2>, user = 'admin', pwd = '123456', captcha = '666'\n\n    def test_login2(self, user='admin', pwd='123456', captcha='666'):\n        # 调用登录业务方法---> 验证码不正确\n        self.login.page_login(user, pwd, captcha)\n        self.excepted = '验证码不正确'\n        actual = self.login.page_alertText()\n        sleep(1)\n        self.login.page_alert()\n        try:\n            # 断言\n>           assert self.excepted == actual\nE           AssertionError: assert '验证码不正确' == '验证码不正确，请重新输入'\nE             - 验证码不正确，请重新输入\nE             + 验证码不正确\n\nscripts\\test01_login.py:80: AssertionError"}, "attachments": [{"name": "登录页面截图", "source": "f1e0c199-5092-4810-8f1f-8f175e8da8cf-attachment.png", "type": "image/png"}, {"name": "log", "source": "2d9fac0c-371b-4097-9ef9-4f8581db4fe5-attachment.txt", "type": "text/plain"}], "start": 1618548573111, "stop": 1618548586257, "uuid": "d9e6be37-51d1-4f6b-9d7f-ce1aeee25a43", "historyId": "fec90d8693fabfaecda5c0b66ef2ca3f", "testCaseId": "949b591a01c258a5cf588e6cefaa0426", "fullName": "scripts.test01_login.TestLogin#test_login2", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test01_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "XTZ-20201026FCM"}, {"name": "thread", "value": "7576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test01_login"}]}