{"name": "test_login2", "status": "failed", "statusDetails": {"message": "AssertionError: assert '验证码不正确' == '验证码不正确，请重新输入'\n  - 验证码不正确，请重新输入\n  + 验证码不正确", "trace": "self = <scripts.test01_login.TestLogin testMethod=test_login2>, user = 'admin', pwd = '123456', captcha = '666'\n\n>   ???\nE   AssertionError: assert '验证码不正确' == '验证码不正确，请重新输入'\nE     - 验证码不正确，请重新输入\nE     + 验证码不正确\n\nF:\\project\\pycharmPro\\pythonProject\\pythonProject\\pythonProject\\unittestPro\\scripts\\test01_login.py:78: AssertionError"}, "attachments": [{"name": "登录页面截图", "source": "5beec165-bab6-449a-b66d-4f597904965c-attachment.png", "type": "image/png"}], "start": 1618431747454, "stop": 1618431761192, "uuid": "5f534a72-2e7a-42e6-a361-b36d45171884", "historyId": "fec90d8693fabfaecda5c0b66ef2ca3f", "testCaseId": "949b591a01c258a5cf588e6cefaa0426", "fullName": "scripts.test01_login.TestLogin#test_login2", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test01_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "XTZ-20201026FCM"}, {"name": "thread", "value": "7336-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test01_login"}]}